pipeline:
  docker:
    image: plugins/docker
    repo: registry.liskl.com/llisk/dockerized-racadm
    tag:
      - ${DRONE_BRANCH/master/latest}
      - ${DRONE_BRANCH}.build-${DRONE_BUILD_NUMBER}
    force_tag: true
    storage_driver: overlay
  ecr:
    image: plugins/ecr
    access_key: ${AWS_ECR_ID}
    secret_key: ${AWS_ECR_KEY}
    repo: ${AWS_ECR_REPO}

